# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logReg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.CharField(max_length=255)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logReg_app.User')),
            ],
        ),
    ]
